apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgis
spec:
  selector:
    matchLabels:
      app: postgis
  serviceName: "postgis"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:16-3.4-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: postgres-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgis-secret
                  key: database
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - name: postgis-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgis-pvc
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: local-path-wffc
        resources:
          requests:
            storage: 1Gi 